using System.ComponentModel.DataAnnotations;
using TodoApi.Models;

// File: UserContextHistory.cs
namespace TodoApi.Models
{
    public class UserContextHistory
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string userId { get; set; }  // ID of the user who sent the prompt

        [Required]
        public string userPrompt { get; set; }  // The text the user submitted

        [Required]
        public string agentResponse { get; set; }  // The response generated by the AI

        public DateTime Timestamp { get; set; } = DateTime.UtcNow;  // Optional: Time of interaction
}
}
